# Generated by Django 4.1.7 on 2023-03-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
