# Generated by Django 4.1.7 on 2023-03-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_laboratory_price'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='laboratory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory'),
        ),
    ]
