# Generated by Django 4.1.7 on 2023-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_field_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='reference',
            field=models.CharField(default='No hay referencia', max_length=255),
        ),
    ]
