# Generated by Django 4.1.7 on 2023-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0002_test_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-02-12'),
            preserve_default=False,
        ),
    ]
