# Generated by Django 4.1.7 on 2023-03-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0006_test_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comment',
            field=models.CharField(default='No hay comentarios', max_length=255),
        ),
    ]
