# Generated by Django 4.1.7 on 2023-03-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testsApp', '0006_test_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('measurment', models.CharField(max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsApp.test')),
            ],
        ),
    ]
