# Generated by Django 4.1.7 on 2023-03-10 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clients_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clients',
            name='dpi',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
