# Generated by Django 4.1.7 on 2023-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clients_birth_clients_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
