# Generated by Django 4.1.7 on 2023-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='mail',
            field=models.EmailField(default='n/a', max_length=254),
        ),
    ]
