# Generated by Django 4.1.7 on 2023-03-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clients_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='mail',
            new_name='email',
        ),
    ]
