# Generated by Django 4.1.7 on 2023-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_mail_clients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
